apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx   # Important for Minikube
  rules:
    - host: messaging.local   # Your local domain for testing
      http:
        paths:
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: messaging-app-service   # Your ClusterIP service
                port:
                  number: 8000
